/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iji4qtkIMGx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Gabarito } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function AlternativeHome() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-background border-b px-4 md:px-6 py-4 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <NewspaperIcon className="h-6 w-6" />
          <span className="font-bold text-lg">Journo</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Categories
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Trending
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            About
          </Link>
          <Button variant="secondary" className="px-4 py-2 text-sm">
            Sign In
          </Button>
          <Button className="px-4 py-2 text-sm">Join</Button>
        </nav>
        <Button variant="ghost" size="icon" className="md:hidden">
          <MenuIcon className="h-6 w-6" />
        </Button>
      </header>
      <main className="flex-1">
        <section className="bg-background py-12 md:py-24 lg:py-32">
          <div className="container grid md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4">
              <h1 className="text-4xl md:text-5xl font-bold tracking-tighter">Empowering Independent Journalism</h1>
              <p className="text-muted-foreground text-lg">
                Discover thought-provoking stories and support the voices that matter.
              </p>
              <div className="flex gap-4">
                <Button className="px-6 py-3 text-sm font-medium">Explore Stories</Button>
                <Button variant="secondary" className="px-6 py-3 text-sm font-medium">
                  Become a Writer
                </Button>
              </div>
            </div>
            <img src="/placeholder.svg" width={600} height={400} alt="Hero" className="rounded-xl object-cover" />
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24 lg:py-32">
          <div className="container grid md:grid-cols-[1fr_300px] gap-8">
            <div className="space-y-8">
              <Card className="border-0 shadow-none">
                <CardHeader className="flex items-center gap-4">
                  <Avatar className="w-10 h-10">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <div className="space-y-1">
                    <div className="font-medium">Acme Inc</div>
                    <div className="text-sm text-muted-foreground">Published 2 hours ago</div>
                  </div>
                </CardHeader>
                <CardContent>
                  <h2 className="text-2xl font-bold">The Future of Independent Journalism</h2>
                  <p className="text-muted-foreground mt-2">
                    In a world dominated by corporate media, independent journalists are fighting to bring you the
                    truth. Discover their stories and support their mission.
                  </p>
                </CardContent>
                <CardFooter className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon">
                      <ArrowUpIcon className="w-4 h-4" />
                      <span className="sr-only">Upvote</span>
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ArrowDownIcon className="w-4 h-4" />
                      <span className="sr-only">Downvote</span>
                    </Button>
                  </div>
                  <div className="text-sm text-muted-foreground">123 upvotes • 12 comments</div>
                </CardFooter>
              </Card>
              <Card className="border-0 shadow-none">
                <CardHeader className="flex items-center gap-4">
                  <Avatar className="w-10 h-10">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <div className="space-y-1">
                    <div className="font-medium">Jane Doe</div>
                    <div className="text-sm text-muted-foreground">Published 4 hours ago</div>
                  </div>
                </CardHeader>
                <CardContent>
                  <h2 className="text-2xl font-bold">The Importance of Ethical Reporting</h2>
                  <p className="text-muted-foreground mt-2">
                    In a world of fake news and biased reporting, independent journalists are committed to upholding the
                    highest standards of ethical journalism. Read their stories and support their mission.
                  </p>
                </CardContent>
                <CardFooter className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon">
                      <ArrowUpIcon className="w-4 h-4" />
                      <span className="sr-only">Upvote</span>
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ArrowDownIcon className="w-4 h-4" />
                      <span className="sr-only">Downvote</span>
                    </Button>
                  </div>
                  <div className="text-sm text-muted-foreground">87 upvotes • 6 comments</div>
                </CardFooter>
              </Card>
              <Card className="border-0 shadow-none">
                <CardHeader className="flex items-center gap-4">
                  <Avatar className="w-10 h-10">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <div className="space-y-1">
                    <div className="font-medium">John Smith</div>
                    <div className="text-sm text-muted-foreground">Published 6 hours ago</div>
                  </div>
                </CardHeader>
                <CardContent>
                  <h2 className="text-2xl font-bold">The Rise of Citizen Journalism</h2>
                  <p className="text-muted-foreground mt-2">
                    In an age of social media and instant communication, ordinary citizens are becoming the new
                    watchdogs of society. Discover their stories and how they are challenging the status quo.
                  </p>
                </CardContent>
                <CardFooter className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon">
                      <ArrowUpIcon className="w-4 h-4" />
                      <span className="sr-only">Upvote</span>
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ArrowDownIcon className="w-4 h-4" />
                      <span className="sr-only">Downvote</span>
                    </Button>
                  </div>
                  <div className="text-sm text-muted-foreground">65 upvotes • 9 comments</div>
                </CardFooter>
              </Card>
            </div>
            <div className="space-y-8">
              <Card className="border-0 shadow-none">
                <CardHeader className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">Categories</h3>
                  <Link href="#" className="text-sm text-primary hover:underline" prefetch={false}>
                    View All
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                      Politics
                    </Link>
                    <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                      Technology
                    </Link>
                    <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                      Environment
                    </Link>
                    <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                      Culture
                    </Link>
                    <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                      Business
                    </Link>
                    <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                      Health
                    </Link>
                  </div>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-none">
                <CardHeader className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">Trending</h3>
                  <Link href="#" className="text-sm text-primary hover:underline" prefetch={false}>
                    View All
                  </Link>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <Link
                      href="#"
                      className="flex items-center gap-2 text-sm font-medium hover:underline"
                      prefetch={false}
                    >
                      <TrendingUpIcon className="w-4 h-4 text-primary" />
                      The Future of Independent Journalism
                    </Link>
                    <Link
                      href="#"
                      className="flex items-center gap-2 text-sm font-medium hover:underline"
                      prefetch={false}
                    >
                      <TrendingUpIcon className="w-4 h-4 text-primary" />
                      The Rise of Citizen Journalism
                    </Link>
                    <Link
                      href="#"
                      className="flex items-center gap-2 text-sm font-medium hover:underline"
                      prefetch={false}
                    >
                      <TrendingUpIcon className="w-4 h-4 text-primary" />
                      The Importance of Ethical Reporting
                    </Link>
                  </div>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-none">
                <CardHeader className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">Join the Community</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground mb-4">
                    Sign up to stay up-to-date with the latest stories and connect with other independent journalists.
                  </p>
                  <form className="space-y-4">
                    <Input type="email" placeholder="Enter your email" className="w-full" />
                    <Button className="w-full">Join Now</Button>
                  </form>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 px-4 md:px-6 border-t">
        <div className="container flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 Journo. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm text-muted-foreground hover:underline" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:underline" prefetch={false}>
              Terms
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:underline" prefetch={false}>
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function ArrowDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </svg>
  )
}


function ArrowUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function NewspaperIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-2 2Zm0 0a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h2" />
      <path d="M18 14h-8" />
      <path d="M15 18h-5" />
      <path d="M10 6h8v4h-8V6Z" />
    </svg>
  )
}


function TrendingUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
