/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/L4v4MteT95O
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Separator } from "@/components/ui/separator";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "./ui/input";

export function Home() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-40 border-b bg-background">
        <div className="container flex h-14 items-center justify-between gap-4 px-4 sm:px-6 md:px-8 mx-auto">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <NewspaperIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">The Genuine Journal</span>
          </Link>
          <nav className="hidden ml-1 gap-4 md:flex">
            <Link
              href="#"
              className="text-sm font-medium hover:underline hover:underline-offset-4"
              prefetch={false}
            >
              Home
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline hover:underline-offset-4"
              prefetch={false}
            >
              News
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline hover:underline-offset-4"
              prefetch={false}
            >
              Opinion
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline hover:underline-offset-4"
              prefetch={false}
            >
              Culture
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline hover:underline-offset-4"
              prefetch={false}
            >
              Tech
            </Link>
          </nav>
          <div className="ml-auto flex items-center gap-4">
            <Button variant="ghost" size="icon" className="md:hidden">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle menu</span>
            </Button>
            <Link
              href="#"
              className="hidden rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring md:inline-flex"
              prefetch={false}
            >
              Subscribe
            </Link>
          </div>
        </div>
      </header>
      <main className="flex justify-center">
        <section className="container grid grid-cols-1 gap-8 px-4 py-8 sm:px-6 md:grid-cols-[1fr_300px] md:gap-12 md:px-8 lg:py-12">
          <div className="space-y-4">
            <div className="relative h-[400px] overflow-hidden rounded-lg">
              <img
                src="/placeholder.svg"
                alt="Featured article"
                width={800}
                height={400}
                className="h-full w-full object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent p-6 sm:p-8">
                <div className="flex h-full flex-col justify-end">
                  <div>
                    <div className="inline-block bg-primary px-3 py-1 text-xs font-medium text-secondary" style={{ borderRadius: "999px"}}>
                      Featured
                    </div>
                  </div>
                  <h2 className="mt-2 text-2xl font-bold text-foreground sm:text-3xl">
                    The Future of Journalism: How Independent Reporters are
                    Shaping the News
                  </h2>
                  <div className="mt-4 flex items-center gap-2 text-sm text-muted-foreground">
                    <Avatar className="h-6 w-6">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <span>John Doe</span>
                    <Separator orientation="vertical" />
                    <span>2 days ago</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardContent className="space-y-4">
                  <div className="relative h-[200px] overflow-hidden rounded-t-lg">
                    <img
                      src="/placeholder.svg"
                      alt="Article thumbnail"
                      width={400}
                      height={200}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="px-4 py-2">
                    <div>
                      <h3 className="text-lg font-bold text-foreground">
                        The Rise of Citizen Journalism: How Everyday People are
                        Shaping the News
                      </h3>
                      <p className="mt-2 text-sm text-muted-foreground">
                        In an era of misinformation and corporate media
                        dominance, independent journalists are empowering
                        communities to tell their own stories.
                      </p>
                    </div>
                    <div className="flex items-center justify-between pt-2">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Avatar className="h-6 w-6">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <span>Jane Doe</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon">
                          <ThumbsUpIcon className="h-5 w-5" />
                          <span className="sr-only">Upvote</span>
                        </Button>
                        <Button variant="ghost" size="icon">
                          <ThumbsDownIcon className="h-5 w-5" />
                          <span className="sr-only">Downvote</span>
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-4">
                  <div className="relative h-[200px] overflow-hidden rounded-t-lg">
                    <img
                      src="/placeholder.svg"
                      alt="Article thumbnail"
                      width={400}
                      height={200}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="px-4 py-2">
                    <div>
                      <h3 className="text-lg font-bold text-foreground">
                        Uncovering the Truth: How Investigative Journalism is
                        Holding the Powerful Accountable
                      </h3>
                      <p className="mt-2 text-sm text-muted-foreground">
                        In a world of spin and obfuscation, independent
                        journalists are shining a light on the stories that
                        matter most.
                      </p>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Avatar className="h-6 w-6">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <span>John Smith</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon">
                          <ThumbsUpIcon className="h-5 w-5" />
                          <span className="sr-only">Upvote</span>
                        </Button>
                        <Button variant="ghost" size="icon">
                          <ThumbsDownIcon className="h-5 w-5" />
                          <span className="sr-only">Downvote</span>
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-4">
                  <div className="relative h-[200px] overflow-hidden rounded-t-lg">
                    <img
                      src="/placeholder.svg"
                      alt="Article thumbnail"
                      width={400}
                      height={200}
                      className="h-full w-full object-cover"
                    />
                  </div>
                  <div className="px-4 py-2">
                    <div>
                      <h3 className="text-lg font-bold text-foreground">
                        Amplifying Marginalized Voices: How Independent Media is
                        Giving a Platform to the Underrepresented
                      </h3>
                      <p className="mt-2 text-sm text-muted-foreground">
                        In a media landscape dominated by the elite, independent
                        journalists are ensuring that the stories of the
                        marginalized are heard.
                      </p>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground">
                        <Avatar className="h-6 w-6">
                          <AvatarImage src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <span>Sarah Lee</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon">
                          <ThumbsUpIcon className="h-5 w-5" />
                          <span className="sr-only">Upvote</span>
                        </Button>
                        <Button variant="ghost" size="icon">
                          <ThumbsDownIcon className="h-5 w-5" />
                          <span className="sr-only">Downvote</span>
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
          <div className="space-y-8 md:sticky md:top-8">
            <div className="space-y-4">
              <h3 className="text-lg font-bold text-foreground">
                Trending Topics
              </h3>
              <div className="grid grid-cols-2 gap-2">
                <Link
                  href="#"
                  className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground hover:bg-muted/50"
                  prefetch={false}
                >
                  Politics
                </Link>
                <Link
                  href="#"
                  className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground hover:bg-muted/50"
                  prefetch={false}
                >
                  Environment
                </Link>
                <Link
                  href="#"
                  className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground hover:bg-muted/50"
                  prefetch={false}
                >
                  Technology
                </Link>
                <Link
                  href="#"
                  className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground hover:bg-muted/50"
                  prefetch={false}
                >
                  Social Justice
                </Link>
                <Link
                  href="#"
                  className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground hover:bg-muted/50"
                  prefetch={false}
                >
                  Arts & Culture
                </Link>
                <Link
                  href="#"
                  className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground hover:bg-muted/50"
                  prefetch={false}
                >
                  Health
                </Link>
              </div>
            </div>
            <div className="space-y-4">
              <h3 className="text-lg font-bold text-foreground">
                Popular Authors
              </h3>
              <div className="grid grid-cols-1 gap-4">
                <Link
                  href="#"
                  className="flex items-center gap-4 rounded-md bg-muted p-4 hover:bg-muted/50"
                  prefetch={false}
                >
                  <Avatar className="h-10 w-10">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-sm font-bold text-foreground">
                      John Doe
                    </h4>
                    <p className="text-sm text-muted-foreground">
                      Investigative Journalist
                    </p>
                  </div>
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 rounded-md bg-muted p-4 hover:bg-muted/50"
                  prefetch={false}
                >
                  <Avatar className="h-10 w-10">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-sm font-bold text-foreground">
                      Jane Smith
                    </h4>
                    <p className="text-sm text-muted-foreground">
                      Tech Journalist
                    </p>
                  </div>
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 rounded-md bg-muted p-4 hover:bg-muted/50"
                  prefetch={false}
                >
                  <Avatar className="h-10 w-10">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-sm font-bold text-foreground">
                      Sarah Lee
                    </h4>
                    <p className="text-sm text-muted-foreground">
                      Culture Critic
                    </p>
                  </div>
                </Link>
              </div>
            </div>
            <Card className="space-y-4">
              <CardHeader className="flex items-center justify-between">
                <h3 className="text-lg font-medium">Join the Community</h3>
              </CardHeader>
              <CardContent className="px-6 pb-6">
                <p className="text-muted-foreground mb-4">
                  Sign up to stay up-to-date with the latest stories and connect
                  with other independent journalists.
                </p>
                <form className="space-y-4">
                  <Input
                    type="email"
                    placeholder="Enter your email"
                    className="w-full"
                  />
                  <Button className="w-full">Join Now</Button>
                </form>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 text-center text-sm text-muted-foreground">
        <div className="container mx-auto">
          &copy; 2024 The Genuine Journal. All rights reserved.
        </div>
      </footer>
    </div>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function NewspaperIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-2 2Zm0 0a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h2" />
      <path d="M18 14h-8" />
      <path d="M15 18h-5" />
      <path d="M10 6h8v4h-8V6Z" />
    </svg>
  );
}

function ThumbsDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  );
}

function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
